### ISSUE TITLE
eplabor 상담 필드(요청자 / 관리자 필드) / 교육신청 필드 - 초안

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/eplabor#6]
```
# eplabor 상담DB

# 상담 요청자 노출 필드

enquiry:
  - name: 이름(김아무개)
    email: 이메일(eamil@email.com)
    phone: 전화번호(010-000-0000)
    categories: 상담유형 (임금, 퇴직금, 근로시간, 휴일/휴가/휴직, 해고/징계/인사등, 근로계약/취업규칙등, 4대보험 직장내괴롭힘/성희롱/폭행등, 노조, 산업재해, 기타)
    context: 상담 및 문제 내용(long text)


labor-environment:
  - company_name: 사업장명 (255)
    company_owner: 대표자명 (255)
    company_contacts: 연락처 (255)  
    company_region: 소재지(은평구, 기타, 무응답)
    company_size: 근로자수(무응답, 5인 미만, 5인이상 10인 미만, 10인 이상 30인 미만, 30인 이상 100인 미만, 100인 이상 )
    company_sectors: 부동산업 및 임대업(제조업, 건설업, 도매 및 소매업, 운수업 및 창고업, 숙박 및 음식점업, 출판.영상.방송통신 및 정보서비스, 금융 및 보험업, 전문.과학 및 기술 서비스업,  사업시설관리 및 사업지원서비스업,  공공행정.국방 및 사회보장 행정, 교육서비스업, 보건업 및 사회복지서비스업, 협회 및 단체.기타 개인 서비스업,  부동산업 및 임대업, 예술.스포츠 및 여가관련 서비스업, 무응답) 
   company_years: 운영기간 (4년)
    contract: 근로계약서 작성여부 (작성, 미작성, 미교부, 무응답, 일부작성)
    social-insurance: 4대보험 가입여부 (가입, 미가입, 일부가입, 무응답)
    employment-rules: 취업규칙 작성여부 (작성, 미작성, 게시, 미게시, 무응답)

# 상담 관리자 노출 필드

prescription :
  - reply: 답변 및 관리자 메모
    status: 처리결과(상담종결, 재상담/지속상담, 조정/화해, 규정정비등 지원, 타기관연계 기타)


# eplabor 교육신청 DB

class_participant:
  - name: 이름(김아무개)
    email: 이메일(eamil@email.com)
    phone: 전화번호(010-000-0000)
    class-id: 교육프로그램 id(연결된 교육프로그램)


```
