### ISSUE TITLE
홈페이지 수정 가능하도록

### ISSUE THREAD

**Issue by mozodev** [team-durumi/eplabor#9]
```
slides:
  - title: '슬라이드 #1'
    description: '슬라이드 #1 설명'
    bg: https://images.unsplash.com/photo-1495725274072-fd5d0b961a9f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1068&q=80
    btn_text: ""
    btn_url: ""
  - title: '슬라이드 #2'
    description: '슬라이드 #2 설명'
    bg: https://images.unsplash.com/photo-1529045138962-5f59528258fe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2031&q=80
    btn_text: ""
    btn_url: ""
  - title: '슬라이드 #3'
    description: '슬라이드 #3 설명'
    bg: https://images.unsplash.com/photo-1562492901-e7021f6af8c2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80
    btn_text: ""
    btn_url: ""
center_info:
  - title: 노동상담
    icon: mic
    url: /consulting/info/
  - title: 교육신청
    icon: chat
    url: workshops/
  - title: 알아두면 도움되는 제도
    icon: heart
    url: /consulting/references/
recents:
  - icon: mic
    title: 공지사항
    type: notice
  - icon: chat
    title: 센터소식
    type: news
four_panes:
  - text1: "유산기부 후원자를 위한"
    text2: "헤리티지 클럽"
    bg: "https://www.kfhi.or.kr/asset/images/main/renewal/sec_06_img_01.jpg"
    url: "http://naver.com"
  - text1: "후원을 넘어 가치를 실현하는"
    text2: "필란트로피클럽"
    bg: "https://www.kfhi.or.kr/asset/images/main/renewal/sec_06_img_02.jpg"
    url: "http://naver.com"
  - text1: "더불어 사는 세상을 위해"
    text2: "홍보대사"
    bg: "https://www.kfhi.or.kr/asset/images/main/renewal/sec_06_img_03.jpg"
    url: "http://naver.com"
  - text1: "기아대책과"
    text2: "함께하는 교회"
    bg: "https://www.kfhi.or.kr/asset/images/main/renewal/sec_06_img_04.jpg"
    url: "http://naver.com"
halfhalfs:
  - photo_url: "/uploads/peng034.png"
    photo_left: true
    message_url: "/"
    message_title: "<strong>투명한</strong> 재정보고와 운영으로<br>정직하게 후원금을 사용합니다."
    message_description: |
      기아대책은 미션, 비전, 3대 경영방침, 7대 핵심가치를
      토대로 중장기 전략 수립/사업수행/점검/분석까지
      체계적인 경영관리 프로세스를 운영합니다.
  - photo_url: "/uploads/peng034.png"
    photo_left: false
    message_url: "/"
    message_title: "펭수는 핵노잼?"
    message_description: |
      "귀엽다고 인기는 많지만 어두운 펭수의 그림자를 조망합니다."
```
